"""Add Phase 1 task orchestration fields

Revision ID: d4e8f1a9b2c3
Revises: c9d7e9b6a4f2
Create Date: 2026-02-24 20:00:00.000000

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4e8f1a9b2c3'
down_revision = 'b497b348ebb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new fields to boards table
    op.add_column('boards', sa.Column('preserve_assignment_on_dependency_change', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('boards', sa.Column('auto_promote_review_hours', sa.Integer(), nullable=False, server_default='24'))
    
    # Add claimed_at to tasks table
    op.add_column('tasks', sa.Column('claimed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tasks_claimed_at'), 'tasks', ['claimed_at'], unique=False)
    
    # Add skill_tags to agents table (JSON array for storing skill tag UUIDs)
    op.add_column('agents', sa.Column('skill_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove skill_tags from agents
    op.drop_column('agents', 'skill_tags')
    
    # Remove claimed_at from tasks
    op.drop_index(op.f('ix_tasks_claimed_at'), table_name='tasks')
    op.drop_column('tasks', 'claimed_at')
    
    # Remove new fields from boards
    op.drop_column('boards', 'auto_promote_review_hours')
    op.drop_column('boards', 'preserve_assignment_on_dependency_change')
    
    # ### end Alembic commands ###
